#!/bin/bash

convert icon1024.png -resize '120x120!' icon120.png
convert icon1024.png -resize '80x80!' icon80.png
convert icon1024.png -resize '58x58!' icon58.png
convert icon1024.png -resize '57x57!' icon57.png
convert icon1024.png -resize '29x29!' icon29.png
convert icon1024.png -resize '114x114!' icon114.png
